---
abstract: 'Tools required for GNU style configure scripts on Windows'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-MSYS
recommends:
  Win32::Shortcut: '0'
requires:
  Archive::Zip: '0'
  File::HomeDir: '0'
  File::ShareDir: '0'
  HTTP::Tiny: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/plicease/alien-msys/issues
  homepage: http://perl.wdlabs.com/Alien-MSYS/
  repository: git://github.com/plicease/alien-msys.git
version: '0.05'
